apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: go-server
  name: go-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-server
    spec:
      containers:
      - image: go-server:v1.0.0
        name: go-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MY-PORT
          value: "8080"